#- Criar Realm
#- Criar Client
#- Configurar Login
#- Criar user
#- Alterar senha do user
#- criar role no realm
#- Vincular role ao cliente
#- Entrar no client -> mappers -> add build in, realm roles, mapear para groups


version: "3.7"
services:
  keycloak_container:
    container_name: keycloak_container
    image: jboss/keycloak:9.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  jaeger_container:
    container_name:  jaeger_container
    image: jaegertracing/all-in-one:1.7
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"